# Generated by Django 5.2 on 2025-05-22 03:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransportForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('guide', models.CharField(max_length=50, verbose_name='Guía')),
                ('patent', models.CharField(max_length=10, verbose_name='Patente')),
                ('loading_station', models.CharField(max_length=100, verbose_name='Estación de carga')),
                ('odometer', models.IntegerField(verbose_name='Odómetro')),
                ('fuel_type', models.CharField(choices=[('diesel', 'Diesel'), ('bluemax', 'BlueMax')], max_length=10, verbose_name='Tipo de combustible')),
                ('load_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total de carga')),
                ('image', models.ImageField(blank=True, null=True, upload_to='transport_forms/', verbose_name='Imagen')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
            ],
            options={
                'verbose_name': 'Formulario de Transporte',
                'verbose_name_plural': 'Formularios de Transporte',
                'ordering': ['-created_at'],
            },
        ),
    ]
