# Generated by Django 5.2.1 on 2025-05-22 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportform',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='transport_forms/', verbose_name='Imagen'),
        ),
    ]
