# Generated by Django 5.2 on 2025-05-22 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transportform',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('completed', 'Completado')], default='pending', max_length=20, verbose_name='Estado'),
        ),
    ]
